Created database for subreddits
ucsb-cs156-w22/team02-w22-5pm-3 pull request #34
Opened 2022-02-04 01:31 UTC by qianyouwang

In this PR, the database for collegiatesubreddits is correctly setup. 

Below shows the ability to access the local H2 console.
<img width="1383" alt="Screen Shot 2022-02-03 at 17 28 04" src="https://user-images.githubusercontent.com/56094380/152457471-d43d5aeb-89de-4c2f-a4cf-41e877c1f006.png">

Below shows the ability to access the remote heroku database console. 
<img width="684" alt="Screen Shot 2022-02-03 at 17 30 27" src="https://user-images.githubusercontent.com/56094380/152457574-54a0385b-3f50-4339-9555-9b2b936e66ab.png">

2022-02-04 21:31 UTC, SwiftWinds commented
If you could, please link the issue in future PRs so reviewers can easily see what the acceptance criteria are. Thanks! :)

2022-02-04 21:32 UTC, SwiftWinds requested changes
Please take a look at my comments. Otherwise, lgtm!

2022-02-04 21:32 UTC, SwiftWinds commented on src/main/java/edu/ucsb/cs156/team02/repositories/CollegiateSubredditRepository.java
> +
Unneeded import
```suggestion
```

2022-02-04 21:32 UTC, SwiftWinds commented on src/main/java/edu/ucsb/cs156/team02/entities/CollegiateSubreddit.java
> +  // private boolean done;
Remove commented out lines
```suggestion
```

2022-02-04 21:32 UTC, SwiftWinds commented on src/main/java/edu/ucsb/cs156/team02/entities/CollegiateSubreddit.java
> +import javax.persistence.ManyToOne;
Remove unused imports
```suggestion
```

2022-02-05 00:05 UTC, SwiftWinds commented
(to approve all suggestions at once, go to the files tab and click add suggestion to batch on each one)

2022-02-05 17:53 UTC, tekaireb requested changes
I agree with the comments made by @SwiftWinds. Let me know when the unused imports have been removed so I can merge it.

2022-02-07 20:52 UTC, SwiftWinds approved these changes
thanks for the changes! Lgtm!

2022-02-07 20:53 UTC, tekaireb approved these changes

2022-02-07 20:53 UTC, merged